#apiVersion: v1
#kind: Namespace
#metadata:
#  name: younic
#  labels:
#    app: younic
#---
apiVersion: v1
kind: ConfigMap
metadata:
  name: younic-config
  # namespace: younic
data:
  younic.cms.repository: https://github.com/escv/younic-sample.git
  younic.cms.repository.branch: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: younic-deployment
  #namespace: younic
  labels:
    app: younic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: younic
  template:
    metadata:
      labels:
        app: younic
    spec:
      hostAliases:
        # the is no internet hostname resolving activated. Adjust here the ip of github.com or find any better solution.
        - ip: "192.30.253.112"
          hostnames:
            - "github.com"
      containers:
      - name: younic-container
        image: escv/younic
        ports:
        - containerPort: 8080
        env:
        - name: YOUNIC_CMS_ROOT_GIT
          valueFrom:
            configMapKeyRef:
              name: younic-config
              key: younic.cms.repository
        - name: YOUNIC_CMS_ROOT_GIT_BRANCH
          valueFrom:
            configMapKeyRef:
              name: younic-config
              key: younic.cms.repository.branch
        resources:
          limits:
            memory: "768Mi"
            cpu: "0.2"
        livenessProbe:
          httpGet:
            path: /api/dir/
            port: 8080
        volumeMounts:
          - mountPath: /opt/younic/cms-root
            name: cms-root
      volumes:
      - name: cms-root
        emptyDir:
          medium: Memory
          sizeLimit: "62Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: younic-service
  ##namespace: younic
spec:
  selector:
    app: younic
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30082
