sudo: false

install: gradle wrapper --gradle-version 4.1

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - .gradle
  - $HOME/.gradle

after_success:
  - ./gradlew cobertura coveralls

script: ./gradlew clean test jar coveralls --continue
